# Generated by Django 5.1.1 on 2024-09-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0003_house_pets_allowed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="pets_allowed",
            field=models.BooleanField(
                default=True,
                help_text="Does this house allow pets?",
                verbose_name="Pets Allowed?",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="price_per_night",
            field=models.PositiveIntegerField(
                help_text="Positive Numbers Only", verbose_name="Price"
            ),
        ),
    ]
